### ISSUE TITLE
The latest plugin doesn't work on my end.

### ISSUE THREAD

**Issue by MieSato** [miurahr/omegat-textra-plugin#100]
Yesterday, I downloaded 2022.2.2.jar and tried to use it, but it didn't work for some reason.
OmegaT's machine translation window showed nothing.
I checked OmegaT's Textra setting several times. 

FYI, today I downloaded 2022.2.1.jar, and it works very well.
Now I'm using 2022.2.1.

I use:
Win10, and OmegaT v.5.2.0. (and TexTla's General NT).

**Comment by miurahr** [comment]
Which language combination do you use?

**Comment by miurahr** [comment]
> FYI, today I downloaded 2022.2.1.jar, and it works very well.
Now I'm using 2022.2.1.

Okay, it may be defeat.

**Comment by maabou512** [comment]
Maybe same here. Mine is OmegaT ver. 4.3.2 on Ubuntu 20.04 LTS.  

My I've been using Textra Plugin of  "omegat-textra-plugin-0.10.0.jar", and 
after replaced to  omegat-textra-plugin-2022.2.2.jar, now nothing showed up like @MieSato  .

After reverting, it works fine. 

Thanks.

**Comment by miurahr** [comment]
v2022.2.3 is out with the fix.
https://codeberg.org/miurahr/omegat-textra-plugin/releases/tag/v2022.2.3
