### ISSUE TITLE
ユーザー名, APIキー, APIシークレットが保存されない

### ISSUE THREAD

**Issue by nogajun** [miurahr/omegat-textra-plugin#11]
プラグインを追加して設定から、みんなの自動翻訳のユーザー名、APIキー、APIシークレットを入力しても設定が保存されず、OmegaTを終了して起動すると、また入力する必要がある状態になります。

設定ファイル ~/.omegat/omegat.prefsを見ても`<mt_textra_translate_mode>generalN</mt_textra_translate_mode>`しか保存されていませんでした。

プラグインのソースを見て、以下の3行を追加すると設定が保持されるようになりましたが、なぜでしょうか?

```
    <mt_textra_username>ユーザー名</mt_textra_username>
    <mt_textra_apikey>APIキー</mt_textra_apikey>
    <mt_textra_secret>APIシークレット</mt_textra_secret>
```

環境は以下です。

- Debian GNU/Linux Sid (amd64)
- OpenJDK 11
- OmegaT 4.2.0 (Cross-platform without JRE)

**Comment by miurahr** [comment]
7月上旬に対応予定

**Comment by miurahr** [comment]
保存された設定を取得するコードはここ
https://github.com/miurahr/omegat-textra-plugin/blob/master/src/main/java/tokyo/northside/omegat/textra/OmegatTextraMachineTranslation.java#L79

**Comment by miurahr** [comment]
一度設定画面をださないと保存されないような条件みたいです。

**Comment by MieSato** [comment]
1. Windows10でも全く同じ症状が出ます。OmegaTはv.4.3.2です。
設定ファイルの3行を書き込んだことで毎回APIキーとシークレットを入れなくても大丈夫になりましたが、OmegaTを再起動するたびに設定画面を出して確定する必要があります。

2. MacとOmegaT v.4.3.2の組み合わせでは、さらに深刻です。
設定ファイルに3行を書き込んでも、OmegaTを終了するたびにそのデータが消えます。
再起動のたびに機械翻訳の設定画面でユーザー名、APIキー、シークレットを入れる必要があります。

Google翻訳は全く問題なく使用できます。
古いバージョンのOmegaTを入れ直すことで解決するのであれば、そうしようかと考えています。

**Comment by miurahr** [comment]
設定保存には、プラグイン実装において
https://github.com/omegat-org/omegat/blob/87e8eaf63c552c553536b651334303d41679f389/src/org/omegat/gui/preferences/PreferencesControllers.java#L33-L39

PreferencesController classを実装する必要があるようです。現状、内蔵の機械翻訳モジュールと同等のコードしか実装しておらず、この実装をしていないため、保存されないようです。

サンプル実装を参考に、大幅な書き換えが必要そうです。
https://github.com/omegat-org/omegat/blob/87e8eaf63c552c553536b651334303d41679f389/src/org/omegat/gui/glossary/taas/TaaSPlugin.java#L113

**Comment by miurahr** [comment]
setCredential() method をもちいることで、保存できるように修正できました。
バージョン0.8としてリリースします。
