### ISSUE TITLE
Not working on Mac

### ISSUE THREAD

**Issue by dm8933** [miurahr/omegat-textra-plugin#12]
Hi there. I put the jar file in the folder contents/plugin. But NICT textra is not showing in my MT selections. Do you know why? Thank you so much.

**Comment by miurahr** [comment]
Thank you for a report. Because I don't use Mac so I have not been aware of it.
Does another plugin working, such as an okapi framework?

They said

> On OS X you are recommended to install the plugin to `/Users/<username>/Library/Preferences/OmegaT/plugins`

You mentioned `contents/plugin` which is different with it.

**Comment by dm8933** [comment]
The Google Translate without a Key API is working fine.

**Comment by dm8933** [comment]
Thank you

**Comment by miurahr** [comment]
Do you extract downloaded zip package and copy jar file into `OmegaT.app/Contents/Resources/Java/plugins` folder ? If not, please do that.

**Comment by dm8933** [comment]
I can only find the intellij_forms_rt.jar and pasted it into the folder OmegaT.app/Contents/Java/plugins (there is no folder in Resources). 
There is no OmegaT folder in my Users/Library.

**Comment by miurahr** [comment]
When you download https://github.com/miurahr/omegat-textra-plugin/releases/download/v0.6/omegat-textra-plugin-0.6.zip and extract it, you will find `omegat-textra-plugin-0.6.jar`.
It should be pasted into the plugin folder .
 intellij_forms_rt.jar is not a plugin file.

**Comment by dm8933** [comment]
Hi Miurahr,

THank you so much! It finally solved my problem. The problem was that there is no omegat-textra-plugin-0.6.jar to be found in the link https://github.com/miurahr/omegat-textra-plugin.

Best regards,

Ming



________________________________

**Comment by miurahr** [comment]
> The problem was that there is no omegat-textra-plugin-0.6.jar to be found in the link https://github.com/miurahr/omegat-textra-plugin.

It is because repository has only source files, and building result is a target `omegat-textra-plugin-0.6.jar` file.
You can get a target by building it with a command `./gradlew build` on your development environment(Java Development Kit).

If you are interested in only using it, please visit github's release page.
