### ISSUE TITLE
Improving README.md  

### ISSUE THREAD

**Issue by maabou512** [miurahr/omegat-textra-plugin#15]
Hi, I tried the plugin  and enjoyed its working.  :) 

BTW,  in the first trial, the README.md file served me but it took more time than I think. I believe the file could be better guiding especially for  first-time users.  

-  Specifying filename and its location.
- $HOME/.omegat/plugin  --> $HOME/.omegat/plugins  (typo?)
-  Information to be noticed for users (restrictions , workarounds and so on. ) 
-  Consideration for Japanese users

 I could send PR as my proposal for modification if you don't mind,  please review that.

**Comment by miurahr** [comment]
PR is always welcome.

**Comment by miurahr** [comment]
PR merged. Thanks.
