### ISSUE TITLE
汎用NTを使いたいが汎用NMTが選択されて変更できない

### ISSUE THREAD

**Issue by MieSato** [miurahr/omegat-textra-plugin#24]
**翻訳エンジンの「汎用NT」を選択できない**

**以下を試したが上書きされる**
1. 設定フォルダーの omegat.prefs を開く
2.  <mt_textra_translate_mode>generalN</mt_textra_translate_mode> の行を探す
3.  <mt_textra_translate_mode>generalNT</mt_textra_translate_mode> に変更する
NICTの方によれば、こうすると汎用NTが使われるのではないかとのこと。
これは以下のURLを呼ぶらしい：
https://mt-auto-minhon-mlt.ucri.jgn-x.jp/api/mt/generalNT_en_ja/
4. OmegaTで再読み込みしたり、OmegaTを再起動したりしてみるが汎用NTは使われない
5. omegat.prefs を見ると、以下のように元に戻っている
<mt_textra_translate_mode>generalN</mt_textra_translate_mode>

**望ましい動作**
翻訳エンジンをどこかで選択でき、それが上書きされないこと。

**スクリーンショット*
1. demo画面で、汎用NTと汎用NMTを比較したもの：
![image](https://user-images.githubusercontent.com/25579395/80354236-6d25bc80-88b1-11ea-9c28-3ec9d5140421.png)

2. OmegaT内の機械翻訳結果：
![image](https://user-images.githubusercontent.com/25579395/80354619-f0471280-88b1-11ea-83d8-d2a41452730f.png)

**環境：**
 - OS: Windows10
 - OmegaT: 5.2.0 Latest
 - Java: 1.8.0_242 (64-bit)

**Comment by miurahr** [comment]
```
    public enum Mode {
        /** generic translation.
         * English/Japanese/Chinese/Korean
         */
        generalN,
        /** address translation.
         * Japanese/English
         */
        patentN,
        /** JPO claim translation.
         * Chinese/Japanese
         */
        patent_claimN,
    }
```
 の3種類に対応していますが、それ以外には対応していません。機能拡張のプログラム変更の提案を歓迎します。

**Comment by miurahr** [comment]
![Screenshot from 2020-04-29 21-07-46](https://user-images.githubusercontent.com/123720/80594251-a26f0d80-8a5d-11ea-8bfd-6a04edde74e5.png)
![Screenshot from 2020-04-29 21-08-37](https://user-images.githubusercontent.com/123720/80594257-a6029480-8a5d-11ea-8d3e-675d503a7b1c.png)

**Comment by miurahr** [comment]
汎用NTと汎用NMTそれそれの、ただしい 英語名称もわかれば、ご教示いただきたい。

**Comment by MieSato** [comment]
ありがとうございます。NICTさんからの回答です。
> 名称はそれぞれ「General NT」「General NMT」です。

**Comment by miurahr** [comment]
![Screenshot from 2020-04-30 13-43-53](https://user-images.githubusercontent.com/123720/80672814-ad22b480-8ae8-11ea-9eb1-2880ff4bbf27.png)

 作業開始しました。こんな感じで動いているようにみえています。

**Comment by miurahr** [comment]
[omegat-textra-plugin-0.8.zip](https://github.com/miurahr/omegat-textra-plugin/files/4556184/omegat-textra-plugin-0.8.zip)

 実験的実装です。テストに利用いただけます。

**Comment by MieSato** [comment]
テストした結果、汎用NTを正常に選択でき、使用できました！。
omegat.prefsの該当行もgeneralNTになっていることを確認しました。
迅速なご対応、ほんとうにありがとうございます!!

**Comment by miurahr** [comment]
v0.9.0 released.
