### ISSUE TITLE
Please remove *NMT modes from Textra translation mode option list.

### ISSUE THREAD

**Issue by MieSato** [miurahr/omegat-textra-plugin#28]
**NICT has deleted all NMT translation modes on Nov. 10, so OmegaT can no longer use those modes.**
Please see https://mt-auto-minhon-mlt.ucri.jgn-x.jp/content/menu/

**Remove NMT modes from Textra Configuration window.**

**There is no alternative solutions, but this request doesn't have very high priority.**

**Comment by miurahr** [comment]
I've attached snapshot build artifact in #29 comment.
Could you test with it?
