### ISSUE TITLE
Glossary registration support

### ISSUE THREAD

**Issue by miurahr** [miurahr/omegat-textra-plugin#3]
TexTra has an API to register glossary for source text when send a translation request.

OmegaT Interface IMachineTranslation don't have a way to provide glossary.

**Comment by NICT-Dev** [comment]
TexTra開発、ユーザーインタフェース担当者です。

TexTra Plugin開発者どうしで情報共有するようにと
ご依頼を受けました。

よろしくお願いいたします。

**Comment by NICT-Dev** [comment]
開発依頼者にご相談されると
「用語集の編集機能は不要」と言われるかもしれません。

**Comment by miurahr** [comment]
@NICT-Dev Wrote:
> 開発依頼者にご相談されると「用語集の編集機能は不要」と言われるかもしれません。

It is difficult to understand what you want to mean...  Who is "開発依頼者"? Here is an OpenSource project.

OmegaT, which is an OpenSource Translation Memory  CAT tool,  has a glossary feature and it has also a feature to edit glossary.  When the textra plugin support glossary request to API, an expected results would be better.

(translation)
おっしゃりたいことの意味がわかりません。「開発依頼者」とは、何を指していますか？

OmegaTは、OSSのCATツールで、翻訳メモリを提供していますが、用語集機能を有しております。したがって、用語集APIを通じて、TexTraへの機械翻訳を依頼できることは、有益な翻訳結果を得ることにつながり、望ましいと考えられます。
