### ISSUE TITLE
Support custom machine translation

### ISSUE THREAD

**Issue by miurahr** [miurahr/omegat-textra-plugin#4]
TexTra support custom MT  using user's TM.
https://mt-auto-minhon-mlt.ucri.jgn-x.jp/content/mt/edit_original/index.html

User can add their own name for trasnlation mode.
It is better allowing users to input original mode name.

**Comment by hsugawa8651** [comment]
現時点の「みん翻」の説明によると、例えば、汎用NMT【英語 - 日本語] は、WebAPI の request URLの末尾が generalN_en_ja です。generic_en_ja や minna_en_ja では code=525 や 530 が各々返され、result の text要素は空でした。

**Comment by hsugawa8651** [comment]
WebAPI として genericN を決め打ちする形で書いてみました。
https://github.com/hsugawa8651/omegat-textra-plugin
v0.4n です。

翻訳エンジンをカスタマイズできるようになったので、
最新のAPIに手動で追随するのは難しいと思います。

WebAPI の一覧を出力する API を「みん翻」で提供していただきたいです。

**Comment by miurahr** [comment]
hsugawa8651  本コメントは、もとのカスタムAPI対応という話ではなく、「みん翻」のAPI変更にともなう動作ができなくなった、という問題の報告でしょうか？

**Comment by hsugawa8651** [comment]
既定API に関するコメントは issue #5 に移しました。

**Comment by miurahr** [comment]
API が変更されて、カスタムのサポートが困難なので実装しないこととして、クローズ
