### ISSUE TITLE
[BUG] omegat-textra-plugin-2020.2.1.zip has no omegat-textra-plugin-2020.2.1.jar.

### ISSUE THREAD

**Issue by juggernautjp** [miurahr/omegat-textra-plugin#40]
**Describe the bug**
The release file of omegat-textra-plugin-2020.2.1.zip has no omegat-textra-plugin-2020.2.1.jar.

**To Reproduce**
1. Download omegat-textra-plugin-2020.2.1.zip from the release page.
2. Unzip omegat-textra-plugin-2020.2.1.zip with 7-Zip.

**Expected behavior**
The unzipped files include omegat-textra-plugin-2020.2.1.jar.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows10 1909
 - Java: OpenJDK 15.0.2
 - Version: textra-plugin 2020.2.1

**Additional context**

**Comment by miurahr** [comment]
v2020.2.2 with fix released. hand uploaded artifact that includes jar.

**Comment by miurahr** [comment]
The broken zip file on v2020.2.1 release is removed.
